### ISSUE TITLE
Invero Dev Roadmap

### ISSUE THREAD

**Issue by Arasple** [Arasple/Invero#2]
## Main

- [x] 菜单结构：Events 事件处理
- [x] 菜单结构：Commands 多态命令创建绑定、物品特征绑定 & 聊天绑定
- [x] 结构动作：ANY/ALL/NONE 组合语句
- [x] 会话变量：global@, player@ 前缀的变量经由数据库存储 
- [x] 物品材质 - 头颅 (player_head) 支持
- [x] 物品材质 - 自定义源（custom_source）支持
- [x] 物品显示 - glow, enchants, color, nbt 等额外属性的支持
- [x] 物品材质的多态序列化支持
- [x] 菜单格式配置的极简化（多态序列化）
- [x] 菜单内置脚本的合理实现
- [x] Generator 生成器面板的实现
- [x] IOPanel 交互面板的实现
- [x] 结构动作：多类型、嵌套级输入捕捉器的实现

## Improvements
- [ ] 命令创建的参数类型与自定义消息
- [x] 文档

**Comment by Arasple** [comment]
- [ ] SubIcons 渲染bug
- [ ] GeneratorPanel 支持过滤/排序及Kether 相关动作
- [ ] GeneratorPanel 元素拓展属性测试
- [ ] 简化的 ScrollPanel/FreeformPanel 逻辑概念设计
- [ ] ScrollPanel 功能实现
- [ ] IOPanel 应用场景概念设计
- [ ] IOPanel 功能实现
- [ ] 高级输入捕获器实现
